### PR TITLE
llvm36, llvm37, llvm38: fix code-signing certificate setup check

### PR DESCRIPTION
**Pull request by tee3**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-versions/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?
- [x] Does your submission adhere to Versions "Acceptable Formulae" [guidelines](https://github.com/Homebrew/homebrew-versions/blob/07b17dfb9f1/README.md#acceptable-formulae)?

-----

This applies the same workaround to the llvm (llvm36, llvm37, llvm38 ) formula when enabling LLDB via the `with-lldb` option.

See https://github.com/Homebrew/homebrew-core/issues/680.
See https://github.com/Homebrew/homebrew-core/commit/535e2565f3918ddcabc67ebce8cf9ceea245bb0c

This is tested with

```
brew install llvm36 --with-lld --with-lldb
brew install llvm37 --with-lld --with-lldb
brew install llvm38 --with-lld --with-lldb
```

There are no new audit failures, but there was an existing failure (an additional blank line) that is not fixed in this pull request.

Note that this does not address the fact that llvm35 does not properly require the codesign identity, nor the fact that the main llvm recipe is significantly different from these recipe.  Each recipe defines its own codesign requirement code within the llvmXX recipe.

### CODE REVIEW

**Comment by tee3** [comment]
Note that llvm37 fails to build with these flags enabled (as seen in the CI report above), which llvm36 and llvm38 do.  I don't think my change caused the failure, though it allowed the configuration to be attempted which failed.

What should I do next?

**Comment by MikeMcQuaid** [comment]
> Note that llvm37 fails to build with these flags enabled (as seen in the CI report above), while llvm36 and llvm38 do. I don't think my change caused the failure, though it allowed the configuration to be attempted which failed.

Maybe just make this PR just for those that are succeeding for now and we'll merge it when green and open a new PR just for the failing one and we can do more testing there. Thanks!

**Comment by tee3** [comment]
I'll do that, thanks.

**Comment by tee3** [comment]
Replaced by https://github.com/Homebrew/homebrew-versions/pull/1292 and https://github.com/Homebrew/homebrew-versions/pull/1293.

**Pull request closed without merging**
