### PR TITLE
Add android-ndk-r10d.rb

### PR DESCRIPTION
**Pull request by lnewman-book**
Copied from r10c and updated sha256 and class.

### CODE REVIEW

**Comment by lnewman-book** [comment]
All I did was copy the existing r10c formula.  I'm going to guess this is not sufficient because you now have more strict checks than when r10c formula went in.

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by dunn** [comment]
```
==> audit problems
homebrew/versions/android-ndk-r10d:
 * A `test do` test block should be added
 * Formula should have a desc (Description).
 * object files were linked against system openssl
These object files were linked against the deprecated system OpenSSL.
Adding `depends_on "openssl"` to the formula may help.
  /usr/local/Cellar/android-ndk-r10d/r10d/prebuilt/darwin-x86_64/lib/python2.7/lib-dynload/_hashlib.so
  /usr/local/Cellar/android-ndk-r10d/r10d/prebuilt/darwin-x86_64/lib/python2.7/lib-dynload/_ssl.so

**Comment by DomT4** [comment]
Fixed the `desc` manually. Can't do anything about the OpenSSL link unless upstream give us a nice way to build from source, and the Homebrew core formula doesn't have a test and from prior conversations I'm not sure how much of a real test is possible fresh off the bat. If there is a potential test we'd be happy to take it in Homebrew and backport it to the Versions here.

Merged in https://github.com/Homebrew/homebrew-versions/commit/1861c3ea2f0cc242950e2d565941fbf932200b43. Thank you for your contribution to Versions @lnewman-book! :smiley_cat:

**Comment by lnewman-book** [comment]
Thank you!

**Pull request closed without merging**
