### PR TITLE
Add sip 4.17

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by DomT4** [comment]
We don't really do point releases here any more. Why would you want `4.17` specifically instead of `4.18`?

**Comment by m-kuhn** [comment]
Our CI builds are broken since the update to 2.18 https://travis-ci.org/qgis/QGIS/builds/123309494
In the long run we will need to figure out how to fix it from our side but for now it would be good to be able to re-enable them.

**Comment by mikemcquaid** [comment]
Sorry, we'd rather not include patch releases in this form. Please consider keeping this in your own tap. Sorry!

**Comment by m-kuhn** [comment]
No worries, we're using it from the own repo now. I was proposing it here just in case there's interest.

**Comment by mikemcquaid** [comment]
@m-kuhn cool, thanks!

**Pull request closed without merging**
