### PR TITLE
go 1.7.5

### PR DESCRIPTION
**Pull request by micate**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-versions/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?
- [x] Does your submission adhere to Versions "Acceptable Formulae" [guidelines](https://github.com/Homebrew/homebrew-versions/blob/master/README.md#acceptable-formulae)?

-----

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Would you consider submitting this (and the previous `go` versions) as `go@1.7` etc. to homebrew/core? We've deprecated this repository. Thanks!

**Comment by ilovezfs** [comment]
@JCount is already planning to do these as a set, so this should sit on ice until then.

**Comment by micate** [comment]
@ilovezfs Sorry, I have not noticed that this repos has been `deprecated`. I will close this pr and wait for your works.

**Comment by ilovezfs** [comment]
@micate cool. Thanks for your patience!

**Pull request closed without merging**
