### PR TITLE
cassandra22 2.2.6

### PR DESCRIPTION
**Pull request by djchen**
cassandra22 from 2.2.4 to 2.2.6

### CODE REVIEW

**Comment by djchen** [comment]
What should I set for plist_options in this case?

**Comment by MikeMcQuaid** [comment]
`plist_options :manual => "cassandra -f"`

**Comment by djchen** [comment]
Thanks Mike

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-versions/commit/bb5942d5307f583903e9d524c311709ef488cb9d. Thank you for your contribution to Homebrew @djchen; we appreciate it! :smiley_cat:

**Pull request merged**
