### PR TITLE
subversion16: fix segfault

### LINKED ISSUE #758: subversion16 co Segmentation fault: 11
1. brew install subversion16 && brew unlink subversion && brew link subversion16
2. svn co https://foo/prj prg
Segmentation fault: 11
Logs: https://gist.github.com/8f12eea62d313c620f35

OS X: 10.10.3-x86_64
Xcode: 6.3
CLT: 6.3.0.0.1.1428348375

brew doctor ok
brew --version
0.9.5

### PR DESCRIPTION
**Pull request by DomT4**
Looks like Homebrew's Neon is to blame for subversion16's segfaults on newer platforms. Using the older version of Neon this subversion 'shipped' with resolves the error.

Closes #758.

### CODE REVIEW

**Comment by hayorov** [comment]
brew uninstall subversion16 neon && brew install subversion16:
mbp:~ allexx$ svn co https://some/prj foo
dyld: Library not loaded: /usr/local/lib/libneon.27.dylib
  Referenced from: /usr/local/bin/svn
  Reason: image not found
Trace/BPT trap: 5

Looks like you drop neon dependency at all in 455e034

if make brew install neon
=> Downloading https://homebrew.bintray.com/bottles/neon-0.30.1.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/neon-0.30.1.yosemite.bottle.tar.gz
==> Pouring neon-0.30.1.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/neon/0.30.1: 177 files, 1.4M

I have prev eror Seg 11

May by subversion needs older neon like 0.29?

**Comment by DomT4** [comment]
It isn't merged yet, so the bottles haven't changed, so it's still using the new Neon version it has a problem with. To test this you'll actually need to do something like:

` brew install https://raw.githubusercontent.com/DomT4/homebrew-versions/svn16/subversion16.rb `

**Comment by hayorov** [comment]
yep, install was gone from yours repo.

**Comment by DomT4** [comment]
Try a ` brew update && brew reinstall subversion16 `. If it doesn't work with the same Neon it shipped alongside originally, It's likely that Yosemite support may become nearly impossible to offer.

**Pull request closed without merging**
