### PR TITLE
glfw3: fix static build

### PR DESCRIPTION
**Pull request by ilovezfs**
also add static test

### CODE REVIEW

**Comment by ilovezfs** [comment]
@DomT4 I'm not sure if there's still any need for the patching we were doing, but it caused https://github.com/Homebrew/homebrew-versions/issues/1318.

**Comment by DomT4** [comment]
Old tree:
```
/usr/local/opt/glfw3
├── COPYING.txt
├── INSTALL_RECEIPT.json
├── README.md
├── include
│   └── GLFW
│       ├── glfw3.h
│       └── glfw3native.h
└── lib
    ├── cmake
    │   └── glfw3
    │       ├── glfw3Config.cmake
    │       ├── glfw3ConfigVersion.cmake
    │       ├── glfw3Targets-release.cmake
    │       └── glfw3Targets.cmake
    ├── libglfw3.3.2.dylib
    ├── libglfw3.3.dylib -> libglfw3.3.2.dylib
    ├── libglfw3.dylib -> libglfw3.3.dylib
    └── pkgconfig
        └── glfw3.pc

6 directories, 13 files
```

New tree:
```
~/Downloads/glfw3
└── 3.2
    ├── COPYING.txt
    ├── INSTALL_RECEIPT.json
    ├── README.md
    ├── include
    │   └── GLFW
    │       ├── glfw3.h
    │       └── glfw3native.h
    └── lib
        ├── cmake
        │   └── glfw3
        │       ├── glfw3Config.cmake
        │       ├── glfw3ConfigVersion.cmake
        │       ├── glfw3Targets-release.cmake
        │       └── glfw3Targets.cmake
        ├── libglfw.3.2.dylib
        ├── libglfw.3.dylib -> libglfw.3.2.dylib
        ├── libglfw.dylib -> libglfw.3.dylib
        └── pkgconfig
            └── glfw3.pc

7 directories, 13 files
```

Looks like this change effectively renames the library.

**Comment by ilovezfs** [comment]
@DomT4 yep. upstream intentionally gives the static and dylib two different name. I have no idea why anyone was trying to mess with that.

**Comment by DomT4** [comment]
Possibly worth bumping the revision if we're changing the primary `.dylib` versioning, and trying to build the `glbinding` formula with the `glfw3` option just to check it can still sniff it out alright.

This formula can actually go live in `homebrew/core` now really, but nobody's really put the effort into moving it across yet, including me.

**Comment by apjanke** [comment]
Ping?

**Comment by MikeMcQuaid** [comment]
@ilovezfs Thoughts here?

**Comment by ilovezfs** [comment]
This formula should probably supplant the formula in core, and the upstream-undermining patch should go bye-bye.

**Comment by MikeMcQuaid** [comment]
👍 from me.

**Comment by ilovezfs** [comment]
Closing in favor of @JCount's superseding PR's:

https://github.com/Homebrew/homebrew-core/pull/7484
https://github.com/Homebrew/homebrew-versions/pull/1470

**Pull request closed without merging**
