### PR TITLE
llvm 3.9.0

### LINKED ISSUE #1388: add llvm39
LLVM 3.9 Was realesed. 

It's [problematic](https://github.com/Homebrew/homebrew-core/pull/4579) to update normal `llvm` package to 3.9, but it should be easy to just deploy it as `llvm39` package.

### PR DESCRIPTION
**Pull request by Godin**
Based on existing `llvm38`.

This closes #1388.

### CODE REVIEW

**Comment by Godin** [comment]
Oops, actually duplicate of #1384

**Comment by Marqin** [comment]
I think you should reopen this, because #1384 is not maintained.

**Comment by MikeMcQuaid** [comment]
@Marqin Feel free to open a new PR.

**Comment by Marqin** [comment]
@MikeMcQuaid I'm not proficient enough in LLVM to know how to configure new version properly. And given LLVM is big project, than much could have changed.

**Comment by Godin** [comment]
@Marqin Excuse me, but then could you please stop dictating what others should do - this is not really helping. You need to patiently wait while others do their best in configuring new version properly, exactly because this is not that easy and "LLVM is big project".

**Comment by Marqin** [comment]
@Godin no. I'll say what I think is good for the project.

**Comment by DomT4** [comment]
There's decent process ongoing in https://github.com/Homebrew/homebrew-core/pull/4579.

@MikeMcQuaid If we want to add a versioned formulae I'd be tempted by `llvm@3.9` in core at this point. There's enough support in place to start using that system a teeny bit more broadly IMO.

**Comment by MikeMcQuaid** [comment]
> @MikeMcQuaid If we want to add a versioned formulae I'd be tempted by llvm@3.9 in core at this point. There's enough support in place to start using that system a teeny bit more broadly IMO.

@DomT4 Yes, please 😁

**Pull request closed without merging**
