### PR TITLE
mariadb100 10.0.24

### PR DESCRIPTION
**Pull request by kuahyeow**

### CODE REVIEW

**Comment by kuahyeow** [comment]
Build fails in all three platforms

```
/tmp/mariadb10020160318-74190-kqtscl/mariadb-10.0.24/storage/connect/tabmysql.cpp:337:48: error: cannot initialize a parameter of type 'PSZ' (aka 'char *') with an rvalue of type 'const char *'
    Database = GetStringCatInfo(g, "Database", Schema ? Schema : "*");
                                               ^~~~~~~~~~~~~~~~~~~~~
/tmp/mariadb10020160318-74190-kqtscl/mariadb-10.0.24/storage/connect/reldef.h:51:53: note: passing argument to parameter 'sdef' here
  char   *GetStringCatInfo(PGLOBAL g, PSZ what, PSZ sdef);
                                                    ^
1 error generated.
```

**Comment by kuahyeow** [comment]
https://jira.mariadb.org/browse/MDEV-9603 :(

**Comment by DomT4** [comment]
Feel free to apply the proposed patch there! You should be able to do a simple `inreplace` by the looks of it. Try:

```ruby
inreplace "storage/connect/tabmysql.cpp", 'Schema ? Schema : "*");', 'Schema ? Schema : (PSZ)"*");'
```

**Comment by kuahyeow** [comment]
Thanks, I'll give that a try. Looks like the ticket was resolved slightly differently - see https://github.com/MariaDB/server/blob/10.0/storage/connect/tabmysql.cpp#L337.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-versions/commit/20adb0371a593d2ad2d71fce5e93d12ebe032783. Thank you for another contribution to Homebrew @kuahyeow! :smiley_cat:

**Pull request closed without merging**
