### PR TITLE
Postgresql 9.3

### PR DESCRIPTION
**Pull request by sigerello**
Added Postgresql 9.3

### CODE REVIEW

**Comment by jsnrth** [comment]
I would find this useful. The CI build link gives me a 404 -- @sigerello any idea why it's failing? Any eta on when it can get fixed and merged? Happy to help if I can. -j

**Comment by sigerello** [comment]
If I remember correctly, build was failing on mountain lion with error similar to this one: https://groups.google.com/forum/#!msg/brew-test-bot/sehQ_7kdsMo/iTx8Msy1MaoJ
But I've installed this formula on yosemite without any problems.
@jacknagel can you check it please? Let me know if I can help somehow.

**Comment by sigerello** [comment]
@mikemcquaid Thanks for pointed me out to style issues. I've fixed them. But now it fails as before on mountain lion with the following error:
```

Error Message

failed: brew audit postgresql93 --strict
Stacktrace

        Error: 1 problems in 1 formulae

==> audit problems
postgresql93:
 * Header files that shadow system header files were installed to "/usr/local/Cellar/postgresql93/9.3.5/include"
The offending files are:
  /usr/local/Cellar/postgresql93/9.3.5/include/ecpg_config.h
  /usr/local/Cellar/postgresql93/9.3.5/include/ecpg_informix.h
  /usr/local/Cellar/postgresql93/9.3.5/include/ecpgerrno.h
  /usr/local/Cellar/postgresql93/9.3.5/include/ecpglib.h
  /usr/local/Cellar/postgresql93/9.3.5/include/ecpgtype.h
  /usr/local/Cellar/postgresql93/9.3.5/include/libpq/libpq-fs.h
  /usr/local/Cellar/postgresql93/9.3.5/include/libpq-events.h
  /usr/local/Cellar/postgresql93/9.3.5/include/libpq-fe.h
  /usr/local/Cellar/postgresql93/9.3.5/include/pg_config.h
  /usr/local/Cellar/postgresql93/9.3.5/include/pg_config_manual.h
  /usr/local/Cellar/postgresql93/9.3.5/include/pg_config_os.h
  /usr/local/Cellar/postgresql93/9.3.5/include/pgtypes_date.h
  /usr/local/Cellar/postgresql93/9.3.5/include/pgtypes_error.h
  /usr/local/Cellar/postgresql93/9.3.5/include/pgtypes_interval.h
  /usr/local/Cellar/postgresql93/9.3.5/include/pgtypes_numeric.h
  /usr/local/Cellar/postgresql93/9.3.5/include/pgtypes_timestamp.h
  /usr/local/Cellar/postgresql93/9.3.5/include/postgres_ext.h
  /usr/local/Cellar/postgresql93/9.3.5/include/sql3types.h
  /usr/local/Cellar/postgresql93/9.3.5/include/sqlca.h
  /usr/local/Cellar/postgresql93/9.3.5/include/sqlda-compat.h
  /usr/local/Cellar/postgresql93/9.3.5/include/sqlda-native.h
  /usr/local/Cellar/postgresql93/9.3.5/include/sqlda.h
```

**Comment by mikemcquaid** [comment]
You can ignore that error as I'm pretty sure it's just how that box has been configured.

**Comment by mikemcquaid** [comment]
Great work here, thanks!

**Comment by TechFounder** [comment]
Thanks guys!!!

**Comment by TechFounder** [comment]
@mikemcquaid When will 93 show up when you search on the command line?

**Comment by mikemcquaid** [comment]
Now.

**Comment by TechFounder** [comment]
Hum, I've been checking for the past few minutes, nothin'. And now I'm getting this:
```
Error: GitHub API rate limit exceeded for 72.227.xxx.xxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
Try again in 50 minutes 6 seconds, or create an API token:
  https://github.com/settings/applications
and then set HOMEBREW_GITHUB_API_TOKEN.
```

**Comment by mikemcquaid** [comment]
`brew install homebrew/versions/postgresql93`

**Comment by TechFounder** [comment]
I was waiting for it show up but it's still missing:
```
Error: No available formula for postgresql93 
Please tap it and then try again: brew tap homebrew/versions
Searching formulae...
Searching taps...
```

**Comment by mikemcquaid** [comment]
`brew update`

**Comment by TechFounder** [comment]
Yea, that did it. Thanks!

**Comment by sigerello** [comment]
@mikemcquaid Probably you are right – there is something wrong with mountain lion setup on CI server: postgres 8, 9 and 9.1 fails the same way as 9.3 on mountain lion. But 9.2 has some different error.

**Comment by scottjacobsen** [comment]
:heart:

**Comment by jsnrth** [comment]
Thanks for this! -j

**Pull request closed without merging**
