### PR TITLE
Reinstate mongo26

### PR DESCRIPTION
**Pull request by pt-stripe**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-versions/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?
- [X] Does your submission adhere to Versions "Acceptable Formulae" [guidelines](https://github.com/Homebrew/homebrew-versions/blob/master/README.md#acceptable-formulae)?

-----

I'd like to still be able to use mongodb26. Is this feasible? I made the formula just by bringing back the old one from ffd1baca844f6af6771e20760d65a73ca2c4bdb7

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Is this version still supported by upstream? I can't find anywhere on their site stating this is the case. Regardless, given it still builds I'm probably OK with including it but as this repo is deprecated it would be great if you could migrate it to homebrew/core like https://github.com/Homebrew/homebrew-versions/pull/1507 and https://github.com/Homebrew/homebrew-core/pull/8630. Thanks and shout if I can help.

**Comment by pt-stripe** [comment]
Will homebrew take old versions as PRs? I only see `./Formula/mongodb.rb` in there not even 3.0, so I'm a little gunshy of pushing 2.6 to them. Should I not be?

**Comment by MikeMcQuaid** [comment]
We're migrating old versions into homebrew/core and will accept older versions that are widely used and build on all platforms.

**Comment by MikeMcQuaid** [comment]
> Is this version still supported by upstream? I can't find anywhere on their site stating this is the case. Regardless, given it still builds I'm probably OK with including it but as this repo is deprecated it would be great if you could migrate it to homebrew/core like #1507 and Homebrew/homebrew-core#8630. Thanks and shout if I can help.

If this is still supported by upstream we'll review it on homebrew/core, thanks!

**Pull request closed without merging**
