### PR TITLE
Sphinx 2.0.8

### PR DESCRIPTION
**Pull request by shosti**
New versions aren't completely backward-compatible.

### CODE REVIEW

**Comment by DomT4** [comment]
Hi! If this is still useful please address any comments ` brew audit --strict ` has locally, Thanks!

**Comment by DomT4** [comment]
Closing per inactivity. Please feel free to request reopening or open a new PR if you're still interested - If you do, please fix any comments ` brew audit --strict ` has, Thanks!

**Comment by chaimleib** [comment]
I am interested! Could we reopen this?

**Comment by mikemcquaid** [comment]
@chaimleib Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Pull request closed without merging**
