### PR TITLE
~ Add a point mentioning the preferred commit message style

### PR DESCRIPTION
**Pull request by PikachuEXE**
Added a point according to
https://github.com/Homebrew/homebrew-versions/pull/896#issuecomment-120807570

### CODE REVIEW

**Comment by DomT4** [comment]
We added this a while ago in https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged in the core.

I'm not sure whether it's helped or not; I increasingly get the feeling people ignore the extensive documentation most of the time :cry:

**Comment by PikachuEXE** [comment]
I don't think it mentioned the style for new formula.
Also I can't find a link in `homebrew-versions`'s `README` (nor `homebrew`'s `README`)
It's best to add links before complaining about people not reading it :D

BTW not sure how to make something like https://github.com/rails/rails/issues/new (guidelines for contributing)

**Comment by PikachuEXE** [comment]
Test-Bot failed with another exception again :confused:

**Comment by DomT4** [comment]
Passing on this for now. A significant documentation shake-up is in the works.

**Pull request closed without merging**
