### PR TITLE
python2.7.10

### PR DESCRIPTION
**Pull request by xcolwell**
The python 2.7.11 in brew introduces this error into some programs:

```
ImportError: dlopen(/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
```

2.7.10 does not have this error.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
We don't want to accept differing patch versions in homebrew-versions, I'm afraid.

**Comment by xcolwell** [comment]
Just curious - why?

By the way, should this also work?

```
brew tap xcolwell/homebrew-versions
brew install xcolwell/homebrew-versions/python2.7.10
```

But really `xcolwell/homebrew-versions` gets written as `xcolwell/versions` and no matter which I use, I get no install and the same output:

```
Error: No available formula with the name "xcolwell/versions/python2.7.10"
==> Searching for similarly named formulae...
This similarly named formula was found:
xcolwell/versions/python2.7.10
To install it, run:
  brew install xcolwell/versions/python2.7.10
==> Searching taps...
Error: No formulae found in taps.
```

**Comment by mikemcquaid** [comment]
@xcolwell Hopefully this explains a bit: https://github.com/Homebrew/homebrew-versions#acceptable-formulae

**Comment by DomT4** [comment]
See also:

* https://github.com/Homebrew/homebrew-versions/pull/513#issuecomment-75676199
* https://github.com/Homebrew/homebrew-versions/pull/967#issuecomment-140919714
* https://github.com/Homebrew/homebrew-versions/pull/882#issuecomment-119012686

**Pull request closed without merging**
