### PR TITLE
bind 9.9.7

### PR DESCRIPTION
**Pull request by seanchannel**
"BIND 9.9.7 is now available"
https://lists.isc.org/pipermail/bind-announce/2015-February/000944.html

### CODE REVIEW

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by seanchannel** [comment]
I can't tell what the failure is here. this built fine on my system.

**Comment by DomT4** [comment]
It's an audit failure rather than an install failure. Cut the ` version "9.9.7" ` line and it'll be fine - The version line isn't necessary when the Bot can read the version from the URL okay.

**Comment by seanchannel** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
> test this please

Afraid the test-bot will ignore you unless you have write access to the repository. I did not know this for a while and spent several PRs asking the bot to do stuff and then wondering why I was getting ignored :wink:. Your new commit will have triggered a new SHA1 though, which will have triggered the bot automatically :).

**Comment by seanchannel** [comment]
thanks much @DomT4 !! 
I had my doubts. =]

**Comment by DomT4** [comment]
Merged! Thanks for your contribution to Homebrew, we appreciate it! :smiley_cat:

**Pull request closed without merging**
