### PR TITLE
node04: build adjustments

### PR DESCRIPTION
**Pull request by DomT4**
This formula is completely dead on my machine. Nothing Homebrew related, It just won't build any more. Fails on one of the internal deps, with a *long* list of compile warnings.

If it fails on all three build bots, We can either MMOS Req it or boneyard it completely, I guess.

### CODE REVIEW

**Comment by DomT4** [comment]
Yup, fails. Any thoughts on boneyard/deletion/MMOS Req since we can't do anything with this on any of the three systems we can test @jacknagel @mikemcquaid?

**Comment by jacknagel** [comment]
>The build-tool has reset ENV. --env=std required.

Try `env :std`? Failing that, boneyard it.

**Comment by DomT4** [comment]
Gave it a whirl locally without any luck. Have pushed here to see if it fixes the failure on <10.10 at all. Thanks for the feedback! :)

**Comment by DomT4** [comment]
Colour me surprised, that fixed the 10.8 build. Guess we can MMOS Req it then.

**Pull request closed without merging**
