### PR TITLE
android-ndk-r10d (new formula)

### PR DESCRIPTION
**Pull request by dalinaum**
It is based on https://github.com/Homebrew/homebrew/commit/074012a831a8d8d7bfd69d3fefb5a089e97add45 and https://github.com/Homebrew/homebrew/commit/8dd3478131b232553f4c0cab197f8443a0a559a6

### CODE REVIEW

**Comment by cmelchior** [comment]
AFAIK we need to upgrade the NDK version used by core as well before we can merge this.

**Comment by dalinaum** [comment]
`These object files were linked against the deprecated system OpenSSL.`

How can I resolve this problem?

**Comment by dunn** [comment]
If these are pre-compiled executables, probably nothing.  We might have to ignore the audit in this case.

**Comment by dalinaum** [comment]
Actually I added the following simple test.

```
test do
  shell_output("#{bin}/ndk-build --help > test.txt")
  assert File.read("test.txt").start_with?("Usage")
end
```

How about adding this @DomT4 ?

**Comment by DomT4** [comment]
@dalinaum Does:

```ruby
test do
  assert_match /Usage/, shell_output("#{bin}/ndk-build --help)
end
```
Not work?

**Comment by dalinaum** [comment]
@DomT4 Thanks. It works!

**Pull request closed without merging**
