### PR TITLE
Grails 2.0.1

### PR DESCRIPTION
**Pull request by kflorence**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Why do you need 2.0.1 specifically rather than 2.0.4, out of interest?

**Comment by kflorence** [comment]
@mikemcquaid That is the version we are stuck with for our legacy Grails site, so unfortunately I can't use 2.0.4.

**Comment by mikemcquaid** [comment]
I'm wondering if this will have widespread use as a Homebrew formula or if it's maybe better vendored in projects?

**Comment by kflorence** [comment]
@mikemcquaid does it really matter? Shouldn't homebrew versions support any older version?

**Comment by mikemcquaid** [comment]
CC @DomT4 for thoughts.

**Comment by DomT4** [comment]
Passing under [new guidelines we've agreed and committed](https://github.com/Homebrew/homebrew-versions#acceptable-formulae), which should make future discussions a little clearer. Sorry, and thanks for the submission to Homebrew!

**Pull request closed without merging**
