### PR TITLE
gnuplot4 4.6.7 (new formula)

### PR DESCRIPTION
**Pull request by equal-l2**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-versions/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?
- [x] Does your submission adhere to Versions "Acceptable Formulae" [guidelines](https://github.com/Homebrew/homebrew-versions/blob/master/README.md#acceptable-formulae)?

-----

Based on https://github.com/Homebrew/homebrew-versions/blob/5313f1803311498633da9bcef463cf233a3506e5/gnuplot4.rb

Changes:
- Bumped version from 4.6.6 to 4.6.7
- Omitted Qt support, since qt4 is no longer supported on Homebrew, and gnuplot4 doesn't support qt5.
- Removed unneeded options.
- Now builds without outdated tutorials

### CODE REVIEW

**Comment by equal-l2** [comment]
Audit says as below, though they are copied by brew itself.
```
  * Emacs Lisp files were linked directly to /usr/local/share/emacs/site-lisp
    This may cause conflicts with other packages.
    They should instead be installed into:
    /usr/local/Cellar/gnuplot4/4.6.7/share/emacs/site-lisp/gnuplot4
    
    The offending files are:
      /usr/local/Cellar/gnuplot4/4.6.7/share/emacs/site-lisp/gnuplot-gui.el
      /usr/local/Cellar/gnuplot4/4.6.7/share/emacs/site-lisp/gnuplot-gui.elc
      /usr/local/Cellar/gnuplot4/4.6.7/share/emacs/site-lisp/gnuplot.el
      /usr/local/Cellar/gnuplot4/4.6.7/share/emacs/site-lisp/gnuplot.elc
```

Can I fix this?

**Comment by MikeMcQuaid** [comment]
CC @dunn for thoughts/help.

**Comment by dunn** [comment]
Adding `--with-lispdir=#{elisp}` to the configure arguments should do it.

**Comment by equal-l2** [comment]
@dunn 
Thank you for help.
It worked like a charm.

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
