### PR TITLE
Add android-ndk-r10e formula

### PR DESCRIPTION
**Pull request by zaki50**
Copied and updated android-ndk-r10d to android-ndk-r10e.
32 bit platform support is removed from r10e.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Could you also remove two of the other versions i.e. https://github.com/Homebrew/homebrew-versions/blob/master/android-ndk-r9d.rb https://github.com/Homebrew/homebrew-versions/blob/master/android-ndk-r10c.rb or https://github.com/Homebrew/homebrew-versions/blob/master/android-ndk-r10d.rb in this PR? Thanks!

**Comment by zaki50** [comment]
@mikemcquaid done. Could you check the PR?

**Comment by mikemcquaid** [comment]
Looks good. Will just wait for CI.

**Comment by zaki50** [comment]
retest this please

**Comment by zaki50** [comment]
I made some mistakes...
I'll fix soon.

**Comment by zaki50** [comment]
retest this please

**Comment by zaki50** [comment]
CI aerver says

```

==> audit problems
homebrew/versions/android-ndk-r10e:
 * object files were linked against system openssl
These object files were linked against the deprecated system OpenSSL.
Adding `depends_on "openssl"` to the formula may help.
  /usr/local/Cellar/android-ndk-r10e/r10e/prebuilt/darwin-x86_64/lib/python2.7/lib-dynload/_hashlib.so
  /usr/local/Cellar/android-ndk-r10e/r10e/prebuilt/darwin-x86_64/lib/python2.7/lib-dynload/_ssl.so
```

Should I add `depends_on "openssl"`?

**Comment by mikemcquaid** [comment]
@zaki50 That can be ignored. Someone will merge this likely as-is (I'm on vacation with too bad internet to do it myself). Thanks!

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-versions/commit/4893fabdc5571063d3f1acfc9338dcae4c55081b. Thank you for your contribution to Homebrew @zaki50; we appreciate it! :smiley_cat:

**Pull request closed without merging**
