### PR TITLE
guile18: added test

### PR DESCRIPTION
**Pull request by DomT4**
Tests, bottles, style fixups, etc.

### CODE REVIEW

**Comment by DomT4** [comment]
The build keeps timing out here because ` guile ` takes *forever* to build, which is why I wanted to bottle it in the first place. Have tried a build with just guile in to see if that works.

**Comment by DomT4** [comment]
@mikemcquaid Any way we can extend the bot's timeout process a little here? ` guile18 `'s compile is (barely) over the hour mark, but is hitting the timeout consequently.

**Comment by mikemcquaid** [comment]
@DomT4 Ping me about it in a few days; I'm trying to get the GHC bottles rebuilt now that I've messed around with the build machines a bit (that should make them faster and more stable).

**Comment by DomT4** [comment]
Ah. GHC is a brutal compile :cry:. Wilco on the few days.

**Comment by DomT4** [comment]
@mikemcquaid Ping as requested. Didn't want to ping you over the Easter weekend, I try to let people enjoy the Holiday periods, heh.

**Comment by mikemcquaid** [comment]
@DomT4 Thanks dude! Have bumped the timeout and retried it.

**Comment by DomT4** [comment]
Thanks! Looks good so far. Just about to cross the hour mark. I guess at least the nice thing about the guile versions formulae is that we shouldn't have to deal with updates to it too often.

**Comment by DomT4** [comment]
Yikes. Timed out again. At 2 hours this time :cry:

**Comment by mikemcquaid** [comment]
Increased it to 4 hours. Retry it tomorrow mid-morning when the bot seems quietish.

**Comment by DomT4** [comment]
Thanks! I thought the last time I built guile it was a less than 2 hour process, but apparently not. Will give it a kick tomorrow when there's less work for the bot.

**Comment by DomT4** [comment]
Failed again, on everything except Yosemite. Timeout galore :smile_cat:. I'm tempted to merge the added test bottle-less until we get the machines back at full-tilt; With the previous 4 builds timing out at ~1hr, ~1hr, ~2hr, ~4hr for whatever reason guile is causing the bot some significant angst.

` guile ` compile is odd, because it's not actually a painful compile. The CPU does essentially nothing after ~5 minutes of compile, you get to here:

```
 ramap.doc unif.doc dynl.doc filesys.doc posix.doc net_db.doc socket.doc regex-posix.doc | GUILE="/private/tmp/guile1820150408-12733-1ft882p/guile-1.8.8/pre-inst-guile" ../scripts/snarf-check-and-output-texi          > guile-procedures.texi || { rm guile-procedures.texi; false; }
```

And then you can be sat there waiting for it to finish for anything between ~20 minutes and ~2 hours, usually. But there's no pressure or compile-activity on the CPU at that point. Maybe there's a way to stop it trying to compile docs.

**Comment by mikemcquaid** [comment]
> Failed again, on everything except Yosemite. Timeout galore . I'm tempted to merge the added test bottle-less until we get the machines back at full-tilt

Yeh, they are as good as they are going to be unfortunately.

**Comment by DomT4** [comment]
No dice on getting back VM-less?

**Comment by mikemcquaid** [comment]
Have migrated them to a machine per-VM and the bare metal install (on Yosemite) isn't any slower it seems.

**Comment by DomT4** [comment]
Ah, okay. Guess if we're not seeing any success on ` guile ` on the ~4hr timeout, there's not much point increasing it. Just hogs the bot without seemingly making much progress. Are you happy for just the added test here to be merged and we can come back to bottles at some point in the future?

**Comment by mikemcquaid** [comment]
Yup, go for it.

**Comment by DomT4** [comment]
Cool, will do. Thanks for helping with the timeout issues, appreciated.

**Pull request closed without merging**
