### PR TITLE
MongoDB 3.0.11

### PR DESCRIPTION
**Pull request by alcaeus**
Copied the last 3.0 formula over from homebrew/homebrew and updated the version. There is no 3.0.11 tag for mongodb tools, hence the 3.0.10 version.

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
1 file inspected, no offenses detected
Error: 1 problem in 1 formula

==> audit problems
homebrew/versions/mongodb30:
 * Description is too long. "name: desc" should be less than 80 characters.
Length is calculated as homebrew/versions/mongodb30 + desc. (currently 86)

```

Please run `brew audit --strict` and identify any issue(s) it identifies.

**Comment by alcaeus** [comment]
> Please run `brew audit --strict` and fix any issue(s) it identifies.

For the record, it was the same description as the original package in homebrew. Maybe if the homebrew prefix (`homebrew/versions/mongodb30: `) wouldn't take up 29 of those 80 characters we could even have meaningful descriptions for packages. /rant

**Comment by ilovezfs** [comment]
@alcaeus Think of it as a haiku to please the literary sensibilities of the test-bot.

**Comment by DomT4** [comment]
Is `3.2.x` not compatible with `3.0.x` in some way?

**Comment by alcaeus** [comment]
There are some changes that can cause incompatibilities according to MongoDB: https://docs.mongodb.org/manual/release-notes/3.2-compatibility/

**Comment by alcaeus** [comment]
Any update on this?

**Comment by MikeMcQuaid** [comment]
@BrewTestBot test this please

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format for simple version updates is `mongodb30 3.0.11 (new formula)`. Please complete the issue template in future PRs where this format is detailed in the linked [Contributing guidelines](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md). Thanks!

**Pull request closed without merging**
