### PR TITLE
gcc5: disable Go support

### LINKED ISSUE #830: Does gcc5's gccgo actually work?
As of gcc 4.9 it didn't. If it doesn't work, we should remove the option.

### PR DESCRIPTION
**Pull request by rhencke**
Closes #830.

### CODE REVIEW

**Comment by rhencke** [comment]
(Sorry, I think I confused the build bot by pushing a new commit to this request mid-build.  Is there a way to re-trigger the build?)

**Comment by DomT4** [comment]
Don't worry about it. We're not updating the bottle since it doesn't change anything that would or wouldn't already be in the bottle, so we can just pull the change.

It passed the one bot which shows you didn't cause any audit failures, and since the `go` build element was never tested in the first place because of it being `optional` I'm happy to pull without an across-the-board green tick.

**Comment by rhencke** [comment]
Much obliged - thank you. :)

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-versions/commit/24ef9ca402cbb8db88b6b78f7b9bec3fc91c9154. Thanks for your contribution to Homebrew, we appreciate it! :smiley_cat:

**Pull request closed without merging**
