### PR TITLE
erlang-r19: 19.0 (new formula)

### PR DESCRIPTION
**Pull request by talentdeficit**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-versions/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?
- [X] Does your submission adhere to Versions "Acceptable Formulae" [guidelines](https://github.com/Homebrew/homebrew-versions/blob/07b17dfb9f1/README.md#acceptable-formulae)?

-----

added because couchdb currently does not build on r19 and is blocking inclusion of this version in the core tap

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Failing on 10.11: http://bot.brew.sh/job/Homebrew%20Versions%20Pull%20Requests/1450/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/install_homebrew_versions_erlang_r19/

@DomT4 thoughts?

**Comment by ilovezfs** [comment]
@MikeMcQuaid 
```
==> Caveats
Man pages can be found in:
  /usr/local/opt/erlang-r19/lib/erlang/man

Access them with `erl -man`, or add this directory to MANPATH.
==> Summary
🍺  /usr/local/Cellar/erlang-r19/19.0: 7,389 files, 277.6M, built in 6 minutes 8 seconds
```
```
OS X: 10.11.5-x86_64
Xcode: 7.3.1
CLT: 7.3.1.0.1.1461711523
```

**Comment by MikeMcQuaid** [comment]
Attempting a rebuild of CI.

**Comment by ilovezfs** [comment]
Now I'm running it through test-bot instead of install and with sandbox set, so we'll see.

**Comment by ilovezfs** [comment]
Yup, also fine via test-bot.

**Comment by talentdeficit** [comment]
do i need to take action on that test failure? i don't quite follow

**Comment by MikeMcQuaid** [comment]
No, it's passing now so can be merged 👍

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-versions/commit/9524246383f17ecc0e64bb2d9e04796375d88ceb. Thank you for your contribution to Homebrew @talentdeficit; we appreciate it! :smiley_cat:

**Comment by rkenzhebekov** [comment]
@talentdeficit, next major version of erlang formula will be called erlang-r20? I'm trying to understand why it's not just erlang instead erlang-r19. 

Thank you

**Comment by talentdeficit** [comment]
@rkenzhebekov i believe it's because there are already two alternate erlang formulas in homebrew-versions. r19 in this case is just shorthand for erlang otp 19.0.1

**Comment by rkenzhebekov** [comment]
@talentdeficit, I got it. Thank you very much!

**Pull request closed without merging**
