### PR TITLE
nu0: fix dead url

### PR DESCRIPTION
**Pull request by DomT4**
The URL is dead and I can't find a mirror for it anywhere. Unless anyone has one, it'll have to be boneyarded.

### CODE REVIEW

**Comment by DomT4** [comment]
CC @Homebrew/owners

**Comment by mistydemeo** [comment]
Macports has it in their distfiles repository: http://distfiles.macports.org/nu/Nu-0.4.0.tgz

**Comment by DomT4** [comment]
Nice! I checked Debian but forgot MacPorts mirror a decent amount of things as well. Thanks Misty, appreciate that.

**Comment by DomT4** [comment]
This is enthusiastically refusing to build for me locally. Doesn't even make it far it before it blows up. I'm going to let the bot run over it to see if it compiles on any of the three OS X versions bottles support, but otherwise we may want to MMOS Req it perhaps?

**Pull request closed without merging**
