### PR TITLE
fix lua53 pkg-config library name

### PR DESCRIPTION
**Pull request by Habbie**

### CODE REVIEW

**Comment by DomT4** [comment]
I'm torn on whether we should do this or just create a `liblua5.3.dylib`. Lua does the former, Lua51 does the latter.

**Comment by Habbie** [comment]
Oh, interesting. I'll try to have a closer look tomorrow.

**Comment by Habbie** [comment]
I see the difference, indeed. Any idea why the lua51 formula has that symlink, instead of fixing the `.pc`? Non pkg-config users expecting it?

**Comment by DomT4** [comment]
Ah, it may well be [our fault](https://github.com/Homebrew/homebrew/blob/be05c000494493a8193a543dc5d78402c8b415d2/Library/Formula/lua51.rb#L163). That patch has been around forever, but we apparently wrote it slightly differently for `lua51` and `lua53`. I'm fairly happy to accept this then. We can re-review if anyone complains, I guess.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-versions/commit/028e86632561f01d4b9451ca6f7e77f25dff671a. Thanks @Habbie! :beer:

**Pull request closed without merging**
