### PR TITLE
Update play13 formula

### PR DESCRIPTION
**Pull request by dcrall**
Updated the play13 formula to pull 1.3.4 instead of 1.3.2. Additionally, the formula is now pulled from Tyrpesafe's site instead of GitHub. This change was made because the compiled version of the framework is not consistently published on GitHub.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
> Additionally, the formula is now pulled from Tyrpesafe's site instead of GitHub. This change was made because the compiled version of the framework is not consistently published on GitHub.

Does this mean it is no longer open source?

**Comment by dcrall** [comment]
The framework is still open source, and the code is on GitHub. However, they don't consistently create the compiled version as one of their release artifacts in the repo. It appears Typesafe expect users to download the compiled version from their site.

**Comment by DomT4** [comment]
This is currently failing because `play14` doesn't exist yet as far as this branch is concerned. It should pass once that PR is merged.

**Comment by mikemcquaid** [comment]
> The framework is still open source, and the code is on GitHub. However, they don't consistently create the compiled version as one of their release artifacts in the repo. It appears Typesafe expect users to download the compiled version from their site.

@dcrall Cool, thanks.

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-versions/commit/bd6501750ef960b8efb4f26154f33f7684d2cdd9. Thanks again!

**Pull request closed without merging**
