### PR TITLE
Postgresql 9.1 (fix styles)

### PR DESCRIPTION
**Pull request by sigerello**
Fixed styles as in #602

### CODE REVIEW

**Comment by sigerello** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
@sigerello The bot is currently having a bit of a bad evening, but I've asked it to take another look here when it's feeling a little better.

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Merged! Thanks for your contribution to Homebrew, we appreciate it! :smiley_cat:

**Pull request closed without merging**
