### PR TITLE
Remove unmaintained Elasticsearch versions

### PR DESCRIPTION
**Pull request by jasontedor**
This commit removes formulae for versions of Elasticsearch that are no
longer actively maintained.

### CODE REVIEW

**Comment by DomT4** [comment]
I couldn't be happier to see all of these go to the big ol' formula graveyard in the sky, but @mikemcquaid may have comment. He did a big cleanup of Elastic stuff in Versions recently.

**Comment by mikemcquaid** [comment]
I'm :+1: on these being :skull:d (selfishly because we don't use these versions). @DomT4 thoughts on whether these should :skull: or move to `homebrew-versions-unsupported`? or `homebrew-versions-boneyard`?

**Comment by DomT4** [comment]
Anything that has an unpatched security hole that has no chance of being patched can :skull: as far as I'm concerned. Anything else can live in `homebrew-versions-unsupported`, which I'll actually go create shortly.

**Comment by mikemcquaid** [comment]
@DomT4 I guess my thinking is: I'm sure those all have similar security problems, even if we don't know about them.

**Comment by mikemcquaid** [comment]
@DomT4 (which isn't an argument against merging this but I think is perhaps an argument against `homebrew-versions-unsupported`

**Comment by jasontedor** [comment]
> Anything that has an unpatched security hole that has no chance of being patched

[Versions < 1.6.1 have known issues](https://www.elastic.co/community/security) that will not be patched, and any unknown issues will also not be patched. Only versions 1.7.x, 2.0.x, and 2.1.x are currently being maintained.

That applies to all of the formulas removed in this pull request.

**Comment by DomT4** [comment]
> which isn't an argument against merging this but I think is perhaps an argument against homebrew-versions-unsupported

I'm willing to draw a narrow distinction between stuff that has security problems and stuff that has security problems that may be intended to be public facing. I appreciate how narrow a distinction this is.

**Comment by mikemcquaid** [comment]
> I'm willing to draw a narrow distinction between stuff that has security problems and stuff that has security problems that may be intended to be public facing. I appreciate how narrow a distinction this is.

That's a reasonable distinction :+1:. We'll be much harsher on servers than libraries/clients. Sounds good.

**Pull request closed without merging**
