### PR TITLE
android-ndk-r12b r12b (new formula)

### PR DESCRIPTION
**Pull request by Naruto**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-versions/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?
- [x] Does your submission adhere to Versions "Acceptable Formulae" [guidelines](https://github.com/Homebrew/homebrew-versions/blob/master/README.md#acceptable-formulae)?

-----

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Please delete `android-ndk-r10e.rb` in this PR, thanks!

**Comment by Naruto** [comment]
@MikeMcQuaid thanks review.
`android-ndk-r10e.rb` is `r10` final version.
I think that homebrew versions should have all major version of `android-ndk`.

**Comment by MikeMcQuaid** [comment]
@Naruto Yep, but we only want 2 versions under the major version, not 3 (which there would be after this PR). Thanks!

**Comment by Naruto** [comment]
@MikeMcQuaid I deleted and `r10e`.

**Comment by MikeMcQuaid** [comment]
Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request merged**
