### PR TITLE
Postgresql 8 (fix styles)

### PR DESCRIPTION
**Pull request by sigerello**
Fixed styles as in #602

### CODE REVIEW

**Comment by DomT4** [comment]
This one needs rebasing against the master.

**Comment by sigerello** [comment]
@BrewTestBot test this please

**Comment by sigerello** [comment]
@DomT4 Sorry, I've messed up here. I've deleted this branch and have created another PR here: #699

**Comment by DomT4** [comment]
No worries, It happens. Thanks for creating the new PR.

**Pull request closed without merging**
