### PR TITLE
allow use with gpgme

### PR DESCRIPTION
**Pull request by jeroenooms**
The current version of gpgme 1.7 has a bunch of new features specifically to work with GnuPG 2.1. See for example the [new keygen functions](https://www.gnupg.org/documentation/manuals/gpgme/Generating-Keys.html). 

I would like to use these features but currently hombrew does not allow installing `gnupg21` alongside `gpgme`.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Do they both `brew link` side-by-side without problem?

**Comment by jeroenooms** [comment]
Yeah I think so, no trouble so far.

**Comment by MikeMcQuaid** [comment]
@jeroenooms I'm not sure how you got this to work given `gpgme` depends on `gnupg2` and there's a `conflicts_with` that too...

**Comment by jeroenooms** [comment]
I did something like this:
```
brew install gpgme
brew remove gpg-agent dirmngr gnupg2
brew install --force gnupg21
```

screen shot 2016-10-12 at 6 37 25 pm

**Comment by jeroenooms** [comment]
Note that recent versions of Debian/Ubuntu have no fully switched to GnuPG 2.1 in combination with GPGME 1.7 as well, if that is any precedent.

**Comment by MikeMcQuaid** [comment]
@jeroenooms That is good precedent, thanks. I think we'll pass on this PR as-is as it requires too many workarounds but the best next step would be to submit one to upgrade to 2.1 in homebrew/core. Thanks!

**Comment by jeroenooms** [comment]
Do you recommend to move `gnupg21` to `homebrew-core`, or simply bump `gnupg2` to version 2.1?

**Comment by MikeMcQuaid** [comment]
Let's try the latter.

**Pull request closed without merging**
