### PR TITLE
qt52: rename d-bus to dbus

### PR DESCRIPTION
**Pull request by miguelarauj1o**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-versions/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?
- [x] Does your submission adhere to Versions "Acceptable Formulae" [guidelines](https://github.com/Homebrew/homebrew-versions/blob/07b17dfb9f1/README.md#acceptable-formulae)?

-----

### CODE REVIEW

**Comment by DomT4** [comment]
Mind adding a `deprecated_option "with-d-bus" => "with-dbus"` here to match the one in the core `qt5`? Thanks!

**Comment by miguelarauj1o** [comment]
@DomT4, sorry for the delay. PR updated.

**Comment by DomT4** [comment]
Heh, looks like this no longer builds on Yosemite or El Cap at all.

**Comment by MikeMcQuaid** [comment]
@DomT4 Maximum OS requirement or just remove it?

**Comment by DomT4** [comment]
Probably a good candidate for MMOSR. Once we start transitioning Versions stuff to the core this'll likely die then, but it's still getting a bit of usage on 10.9.5 according to our usage data.

**Comment by miguelarauj1o** [comment]
Hey @DomT4, what MMOSR mean?

**Comment by DomT4** [comment]
Sorry, so used to truncating it now. `MaximumMacOSRequirement`.

**Comment by apjanke** [comment]
I pulled your changes in to #1342 (preserving your author credit), and it's been merged.

Thank you for your contribution to Homebrew!

**Pull request closed without merging**
