### PR TITLE
Adding ElasticSearch 1.5.2

### PR DESCRIPTION
**Pull request by henrytseng**
Amazon AWS only supports ElasticSearch 1.5.x currently so this will probably be convenient for several developers.

### CODE REVIEW

**Comment by DomT4** [comment]
Is this still supported upstream @jasontedor?

**Comment by jasontedor** [comment]
> Is this still supported upstream

@DomT4 This version is no longer maintained by Elastic. Further, the AWS Elasticsearch service does not support all of the open source Elasticsearch APIs.

**Comment by DomT4** [comment]
Thanks for the quick reply Jason. Passing on this then, I don't really want to support versions upstream no longer does on this.

@henrytseng If you wish to support this, since it doesn't need bottling you can get the same ease-of-access by setting up [your own tap](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md). Thank you for your submission to Homebrew nonetheless!

**Comment by henrytseng** [comment]
Okay!  Welp, if anyone is thinking about using it.  It is here: https://github.com/henrytseng/homebrew-elasticsearch

**Pull request closed without merging**
