### PR TITLE
gcc48: add test

### PR DESCRIPTION
**Pull request by DomT4**
Catch up with audit changes upstream, change to SHA256, add test, change the options to match every other gcc formulae we ship, etc.

### CODE REVIEW

**Comment by DomT4** [comment]
@Homebrew/owners Any objections/consequences to scoping the ` "--with-build-config=bootstrap-debug" ` Yosemite build fix exclusively to Yosemite here? Tried adding an ` LDFLAG ` in #778 but didn't seem to make much difference, but without the ` bootstrap-debug ` fix in the ` gcc48 ` formula the formula doesn't compile on 10.10 at all. I could just be being an idiot and suggesting the wrong ` LDFLAG ` - Feel free to call me an idiot if I'm being one :wink:.

**Comment by mikemcquaid** [comment]
@DomT4 I don't mind, seems fine to me.

**Comment by DomT4** [comment]
Alright, pushed. If it passes the bot and nobody else throws an objection, I'll merge this sometime tomorrow.

**Comment by DomT4** [comment]
Merged.

**Pull request closed without merging**
