### PR TITLE
update gnupg21 from 2.1.12 to 2.1.13

### PR DESCRIPTION
**Pull request by mabels**
- [y] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [y] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-versions/pulls) for the same formula update/change?
- [y] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [y] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?
- [y] Does your submission adhere to Versions "Acceptable Formulae" [guidelines](https://github.com/Homebrew/homebrew-versions/blob/07b17dfb9f1/README.md#acceptable-formulae)?

### CODE REVIEW

**Comment by DomT4** [comment]
`make check` is failing, only on Yosemite. Both Mavericks & El Cap are building fine, which is odd.

```
PASS: tofu.test
FAIL: gpgtar.test
PASS: use-exact-key.test
PASS: default-key.test
    > D74C5F22 C40FDECF ECABF51D <
PASS: export.test
PASS: finish.test
=======================================
1 of 36 tests failed
Please report to https://bugs.gnupg.org
=======================================
make[3]: *** [check-TESTS] Error 1
make[2]: *** [check-am] Error 2
make[1]: *** [check-recursive] Error 1
make: *** [check-recursive] Error 1
```

**Comment by mabels** [comment]
Hi,

this is really odd. I have no access to a Yosemite machine. 
I could try to report this to the gnupg-devel mailing list?

meno

**Comment by DomT4** [comment]
Yeah, that's probably worthwhile. I have access to a Yosemite VM, I'll try and get access to fuller logs later tonight to get a better look at what's happening here.

**Comment by mabels** [comment]
i just reported that to the mailing list.

And referred to this pull request so if you put the logs here they should be able to find them

meno

**Comment by DomT4** [comment]
I can't actually reproduce this locally in a Yosemite VM, which makes me wonder if there's a race condition in play here.

**Comment by DomT4** [comment]
Bingo. 10+ builds later, I finally managed to replicate this a couple of times:

```
Test: gpgtar.test
GNUPGHOME=/private/tmp/gnupg21-20160617-26264-ehu3mc/gnupg-2.1.13/tests/openpgp
gpgtar: gpg: encrypted with 1024-bit ELG key, ID 05A37887B27907AA, created 2003-12-31
gpgtar: gpg:       "Test two (no pp) <two@example.com>"
gpgtar: [?]: warning: name not terminated by a nul byte
gpgtar: [?]: invalid octal number encountered - assuming 0
gpgtar: [?]: invalid octal number encountered - assuming 0
gpgtar: [?]: warning: name not terminated by a nul byte
gpgtar: [?]: invalid octal number encountered - assuming 0
gpgtar: [?]: invalid octal number encountered - assuming 0
gpgtar: [?]: invalid octal number encountered - assuming 0
gpgtar: [?]: invalid octal number encountered - assuming 0
gpgtar: [?]: warning: garbage after name
gpgtar: [?]: invalid octal number encountered - assuming 0
gpgtar: [?]: invalid octal number encountered - assuming 0
gpgtar: error reading '[?]': premature EOF (size of last record: 0)
```

2nd time:

```
Test: gpgtar.test
GNUPGHOME=/private/tmp/gnupg21-20160617-26264-ehu3mc/gnupg-2.1.13/tests/openpgp
gpgtar: gpg: encrypted with 1024-bit ELG key, ID 05A37887B27907AA, created 2003-12-31
gpgtar: gpg:       "Test two (no pp) <two@example.com>"
gpgtar: gpg: encrypted with 1024-bit ELG key, ID 05A37887B27907AA, created 2003-12-31
gpgtar: gpg:       "Test two (no pp) <two@example.com>"
gpgtar: gpg: encrypted with 1024-bit ELG key, ID 05A37887B27907AA, created 2003-12-31
gpgtar: gpg:       "Test two (no pp) <two@example.com>"
gpgtar: gpg: Signature made Fri Jun 17 16:15:24 2016 PDT using RSA key ID D120B626ECABF51D
gpgtar: gpg: Good signature from "Test three (no pp) <three@example.com>" [unknown]
gpgtar: gpg: WARNING: Using untrusted key!
gpgtar: gpg: encrypted with 1024-bit ELG key, ID 05A37887B27907AA, created 2003-12-31
gpgtar: gpg:       "Test two (no pp) <two@example.com>"
gpgtar: gpg: Signature made Fri Jun 17 16:15:24 2016 PDT using RSA key ID D120B626ECABF51D
gpgtar: gpg: Good signature from "Test three (no pp) <three@example.com>" [unknown]
gpgtar: gpg: WARNING: Using untrusted key!
gpgtar: gpg: Signature made Fri Jun 17 16:15:24 2016 PDT using RSA key ID D120B626ECABF51D
gpgtar: gpg: Good signature from "Test three (no pp) <three@example.com>" [unknown]
gpgtar: gpg: WARNING: Using untrusted key!
gpgtar: gpg: Signature made Fri Jun 17 16:15:24 2016 PDT using RSA key ID D120B626ECABF51D
gpgtar: gpg: Good signature from "Test three (no pp) <three@example.com>" [unknown]
gpgtar: gpg: WARNING: Using untrusted key!
gpgtar: gpg: AES encrypted data
gpgtar: gpg: encrypted with 1 passphrase
gpgtar: gpg: AES encrypted data
gpgtar: gpg: encrypted with 1 passphrase
gpgtar: error reading '[?]': premature EOF (size of last record: 0)
```

Race does look possible. Will forward the logs to upstream.

**Comment by DomT4** [comment]
Upstream fixed the issue, and I applied the patch in https://github.com/Homebrew/homebrew-versions/pull/1303. You've still commit credit for this commit, which was merged in https://github.com/Homebrew/homebrew-versions/commit/ffc735058938ad81f4c803d3b83f82945f006157.

Thank you for your patience, and your contribution to Homebrew @mabels! 😺

**Pull request closed without merging**
