### PR TITLE
ruby187: clean up and vendor in rubygems

### PR DESCRIPTION
**Pull request by UniqMartin**
Adapt the formula to make it behave as much as reasonably possible like the core Ruby formula. Vendor in an up-to-date RubyGems installation to make the formula more useful and put Gems outside of cellar to retain them across reinstalls. Consequently, also set Gem binary directory to `HOMEBREW_PREFIX/lib/ruby/gems/ABI_VERSION/bin`, so that wrapper scripts also are retained. (And inform user about this location in caveats.)

Reduce some code duplication by introducing `program_suffix` and `rubygems_bindir`. Also make some minor stylistic adjustments, use a HTTPS download URL, add a description, and slightly beef up the test.

Work around a breakage with `superenv`, where the Homebrew compiler wrappers are broken because `RUBYLIB`/`RUBYOPT` is set in build system.

Fix `test` if option `--with-suffix` is specified.

Fix installation of documentation with option `--with-doc`.

*Note: I picked quite liberally from #1017 and the Ruby formula in Homebrew core. Hope that's okay. I think I was able to resolve all outstanding issues.*

### CODE REVIEW

**Comment by mikemcquaid** [comment]
@UniqMartin you are my hero :heart_eyes:

**Comment by UniqMartin** [comment]
@mikemcquaid Thanks, that's a lovely thing to say! :smile: Glad I could help and thereby also scratch my own itch in getting one of my other PRs merged sooner rather than later.

While working on this PR, I also touched and tested `ruby193`, `ruby20`, and `ruby21` and brought them to the same standards (resolving some issues along the way). Should I open three separate PRs or one PR with three commits? I'm personally leaning towards the latter, as that would focus the discussion and make it easier to see the bigger picture.

**Comment by DomT4** [comment]
>  Should I open three separate PRs or one PR with three commits? I'm personally leaning towards the latter, as that would focus the discussion and make it easier to see the bigger picture.

I'd probably go for three separate PRs to be honest. Some of them have pretty tetchy build processes, and if one fails you end up redoing the a lengthier build over again. Mike can overrule me though.

**Comment by mikemcquaid** [comment]
I think one PR is fine :+1:

**Comment by UniqMartin** [comment]
I have prepared #1028. The bot seems to be happy.

**Pull request closed without merging**
