### PR TITLE
syncthing010: formula description added

### PR DESCRIPTION
**Pull request by miguelarauj1o**
```brew audit --strict syncthing010``` returns:

```
homebrew/versions/syncthing010:
 * Formula should have a desc (Description).
```

--

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew/pulls) for the same update/change?

This PR eliminates the warning.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Build is failing unfortunately, not sure why: http://bot.brew.sh/job/Homebrew%20Versions%20Pull%20Requests/1300/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/install_homebrew_versions_syncthing010/

**Comment by miguelarauj1o** [comment]
I don't know how fix this. @mikemcquaid, can you help me?

**Comment by mikemcquaid** [comment]
Retrying the build. If this still isn't working we'll probably just remove the formula.

**Comment by DomT4** [comment]
I killed it. Thanks for the submission nonetheless @miguelarauj1o, apologies we couldn't accept this one through no fault of your own.

**Pull request closed without merging**
