### PR TITLE
boot2docker 1.6.2 (new formula)

### PR DESCRIPTION
**Pull request by jsnrth**
This is a related formula to docker162, which is added in #877. -j

```
☛ brew audit --strict boot2docker162.rb
==> brew style boot2docker162

1 file inspected, no offenses detected
```

### CODE REVIEW

**Comment by jsnrth** [comment]
I'm unsure why CI failed. Any advice would be helpful. Thanks! -j

**Comment by DomT4** [comment]
Looks like cross-contamination. Have told it to go look again.

**Comment by jsnrth** [comment]
Great, thanks @DomT4 !

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-versions/commit/703941d1b027e79f5aac5a514e866e3ffa8d6082. Thank you for your contribution to Versions, we appreciate it! :smiley_cat:.

Just a nit, but we don't permit `head` installations of Versions formulae unless that branch is specifically pointed to the same release branch of the formula. If a head is pointed at `master` and people want it, they should be using Homebrew's core `boot2docker` formula. Thanks!

**Pull request closed without merging**
