### PR TITLE
mysql51: modernise, move to homebrew openssl by default, audit fixes

### PR DESCRIPTION
**Pull request by DomT4**
Modernises the formula, adds a test, moves to Homebrew's OpenSSL by default (Although still providing an opt-out, for now), passing the `brew audit --strict` test. Will bottle as well.

### CODE REVIEW

**Comment by dnrce** [comment]
@DomT4, is there a reason `--with-partition` was removed from the build config as part of this change?

**Comment by DomT4** [comment]
Rats. Human error. Sorry, will fix that shortly.

**Comment by DomT4** [comment]
Human error = I screwed up :wink:

**Comment by DomT4** [comment]
Do a ` brew install mysql51 ` after #751 is merged and you'll have it back. Apologies again.

**Comment by dnrce** [comment]
Awesome.  Thanks for the very speedy fix!

**Comment by DomT4** [comment]
Should be good now :+1:

**Pull request closed without merging**
