### PR TITLE
Spidermonkey 45 (new formula)

### PR DESCRIPTION
**Pull request by yan12125**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-versions/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?
- [x] Does your submission adhere to Versions "Acceptable Formulae" [guidelines](https://github.com/Homebrew/homebrew-versions/blob/07b17dfb9f1/README.md#acceptable-formulae)?

-----

From ```README.md```:

> newer versions of packages that are too incompatible to go in homebrew/core yet (Such as GnuPG21).

See my comments at https://github.com/Homebrew/homebrew-core/pull/861#issuecomment-239272515. Spidermonkey doesn't keep API compatibilities among different versions, so a versioned formula is necessary for newer Spidermonkey releases.

### CODE REVIEW

**Comment by yan12125** [comment]
Hmm Jenkins does not test ```--HEAD```. Due to https://bugzilla.mozilla.org/show_bug.cgi?id=1296289, header files are missing from a ```--HEAD``` installation. Is it OK?

**Comment by apjanke** [comment]
Is a `head` even appropriate in this case, if the branch it's pointing to doesn't track 45.x development specifically? I don't know how their versioning/API compatibility behaves WRT their development trunk. I'd say probably remove the `head` here.

Otherwise :+1:.

**Comment by yan12125** [comment]
You're right. Basically Mozilla keeps _NO_ API compatibility, so I just removed the ```head``` block.

**Comment by apjanke** [comment]
Merged. Thank you for your contribution to Homebrew!

**Comment by yan12125** [comment]
Thanks :)

**Pull request closed without merging**
