### PR TITLE
New formula: unison 2.40

### PR DESCRIPTION
**Pull request by ummels**
Needed because unison 2.48 is not protocol-compatible with unison 2.40.

### CODE REVIEW

**Comment by DomT4** [comment]
Looks good. Few audit failures to chase up on, but otherwise happy :+1:

```
==> audit problems
unison240:
 * A `test do` test block should be added
 * Use `system "make", "./mkProjectInfo"` instead of `system "make ./mkProjectInfo"` 
 * Use `system "make", "UISTYLE=text"` instead of `system "make UISTYLE=text"` 
```

**Comment by ummels** [comment]
Thanks. I've added a test and made the other two changes.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-versions/commit/6d1b617b2fdafde12553b56460fe8e3ba4f2cf38. Thanks for your contribution to Homebrew, we appreciate it! :smiley_cat:. For future reference please note the preferred styling of commit messages for new formulae is ` unison240 2.40.128 (new formula) ` - Thanks!

**Comment by ummels** [comment]
Thanks!

**Pull request closed without merging**
