### PR TITLE
Play 1.4

### PR DESCRIPTION
**Pull request by dcrall**
New formula, play14, to install the latest version of the Play 1.4 series. The formula was based on the existing play13 formula. However, the download url now points to Typesafe's hosted version as they do not consistently publish the compiled framework on GitHub.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
> However, the download url now points to Typesafe's hosted version as they do not consistently publish the compiled framework on GitHub.

Does this mean this is no longer open-source?

Would be good to remove e.g. `play12` so we only have the current stable +/-2 versions here.

**Comment by DomT4** [comment]
```
homebrew/versions/play14:
  * `desc` (line 5) should be put before `homepage` (line 2)
  * Description is too long. "name: desc" should be less than 80 characters.
    Length is calculated as play14 + desc. (currently 99)
  * 6: Trailing whitespace was found
  * C: 5: col 102: Trailing whitespace detected.
```

**Comment by dcrall** [comment]
Sorry for all the churn on this request. I did see the formula cookbook, but I had already gone down the road of forking the repository, so I was off the documented path. I finally figured out how to run the audit against my forked version.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-versions/commit/805235d010125a68cebe142f2dbbb316644d1d9d. Thank you for your contribution to Homebrew @dcrall; we appreciate it! :smiley_cat:

And yes, I borked fixing the commit message when I squashed the commits together 😅.

**Pull request merged**
