### PR TITLE
llvm36: backport homebrew/homebrew build fixes

### PR DESCRIPTION
**Pull request by DomT4**
See:

* https://github.com/Homebrew/homebrew/pull/39371
* https://github.com/Homebrew/homebrew/issues/37167

### CODE REVIEW

**Comment by DomT4** [comment]
This is on hold until we iron out the kinks discovered in the CMake produced LLVM in Homebrew/homebrew.

Refs:
* https://github.com/Homebrew/homebrew/issues/39609
* https://github.com/Homebrew/homebrew/issues/39612

**Comment by DomT4** [comment]
Hmm. One remaining error:

```
==> make -C /private/tmp/llvm3620150526-80948-1vv2mem/llvm-3.6.0.src/projects/libcxx install CC=/usr/local/Cellar/llvm36/3.6.0/lib/llvm-3.6/bin/clang CXX=/usr/local/Cellar/llvm36/3.6.0/lib/llvm-3.6/bin/clang++ MACOSX_DEPLOYMENT_TARGET=10.8 DSTROOT=/usr/local/Cellar/llvm36/3.6.0/lib/llvm-3.6 SYMROOT=/private/tmp/llvm3620150526-80948-1vv2mem/llvm-3.6.0.src/projects/libcxx
cd lib && ./buildit
./buildit: line 77: /usr/local/Cellar/llvm36/3.6.0/lib/llvm-3.6/bin/clang++: No such file or directory
+ for FILE in '../src/*.cpp'
+ /usr/local/Cellar/llvm36/3.6.0/lib/llvm-3.6/bin/clang++ -c -g -Os -arch i386 -arch x86_64 -nostdinc++ -std=c++11 -fstrict-aliasing -Wall -Wextra -Wshadow -Wconversion -Wpadded -Wstrict-aliasing=2 -Wstrict-overflow=4 -I../include ../src/algorithm.cpp
./buildit: line 138: /usr/local/Cellar/llvm36/3.6.0/lib/llvm-3.6/bin/clang++: No such file or directory
make: *** [install] Error 1
```

**Comment by tamird** [comment]
Why is this formula _so_ different from what's in core?

**Comment by DomT4** [comment]
* Versions formulae of compilers *tend* to have more optional options built-in than the core. Clang, for example, is built by default in Versions' LLVM.
* Versions formulae of compilers *tend* to be built against the available dependencies at the time of upstream release. This essentially means we can update the core without having to stress so much about breaking all of the existing LLVM formulae in Versions.

Neither are hard or fast rules, and the application of the rules vary as to when the formula was last updated/submitted, but to some extent Versions is supposed to be stable long-term whereas the core can be more fluid.

**Pull request closed without merging**
