### PR TITLE
Pandoc cabal_clean_lib fixup

### PR DESCRIPTION
**Pull request by mikemcquaid**
This method was removed from the DSL and these formulae still used it.

CC @DomT4 @tschoonj

### CODE REVIEW

**Comment by DomT4** [comment]
:+1:. Could do with bottles for El Cap here as well when pulled.

**Comment by mikemcquaid** [comment]
@DomT4 From local testing: I suspect they won't build.

**Comment by mikemcquaid** [comment]
https://github.com/Homebrew/homebrew/pull/48479 is another fix for this but both would be best.

**Comment by mikemcquaid** [comment]
As expected: these fail to build so I'm just going to remove them. We should probably avoid adding old versions of stuff that uses `cabal` as they break so easily.

**Pull request closed without merging**
