### PR TITLE
libmongoclient-legacy 1.0.4

### PR DESCRIPTION
**Pull request by billybones256**
Update to latest official driver.

### CODE REVIEW

**Comment by dunn** [comment]
Is it possible to add a test as well? Just something to quickly check basic functionality.

**Comment by billybones256** [comment]
I think no, because user need to have installed mongodb on his computer to pass tests.

**Comment by dunn** [comment]
Something like this should work.  It doesn't do much, but it's better than nothing:
```ruby
  test do
    (testpath/"test.cpp").write <<-EOS.undent
      #include <mongo/client/dbclient.h>

      int main() {
          mongo::DBClientConnection c;
          mongo::client::initialize();
          return 0;
      }
    EOS
    system ENV.cxx, "-L#{lib}", "-lmongoclient",
           "-L#{Formula["boost"].opt_lib}", "-lboost_system",
           testpath/"test.cpp", "-o", testpath/"test"
    system "./test"
  end
```

**Comment by billybones256** [comment]
Ok, I added you code to test section.

**Comment by dunn** [comment]
Merged in bbf8b828f7f6e22993a7deaef0afd26e0993b2bc, thanks!

**Pull request closed without merging**
