### PR TITLE
Various

### PR DESCRIPTION
**Pull request by DomT4**
Bottles, Tests, Style fixes.

Splits #742 in two.

### CODE REVIEW

**Comment by DomT4** [comment]
@mikemcquaid Any idea why the bot's downstream build is failing a fair bit for versions lately? The main build is fine, but the bottle build doesn't upload to Bintray - Just errors out on the ` curl ` stage.

I've tried breaking the larger PRs into smaller PRs, changing the versioning around to see whether the regex is the issue, etc. No dice.

**Comment by mikemcquaid** [comment]
@DomT4 Should be fixed as of https://github.com/Homebrew/homebrew/commit/ed239d1a7e9f70904eb03d3725743e104db384fd

**Comment by DomT4** [comment]
Yup, looks great! Thanks! Was chasing my tail on that for a few days trying to work out what the ` curl ` failure was :smile_cat:.

**Comment by DomT4** [comment]
Rats. New error.

```
==> Fetching imagemagick-ruby186 from homebrew/homebrew-versions
==> Downloading https://homebrew.bintray.com/bottles-versions/imagemagick-ruby186-6.5.9-10.yosemite.bottle.tar.gz

curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "imagemagick-ruby186"
Download failed: https://homebrew.bintray.com/bottles-versions/imagemagick-ruby186-6.5.9-10.yosemite.bottle.tar.gz
Error: Failure while executing: brew fetch --force-bottle imagemagick-ruby186
```

It's published and available, but not downloading. Might ask the bot to do it again, that usually eventually resolves the 401 errors.

**Comment by mikemcquaid** [comment]
You might want to try and wait a few seconds and there may be a delay.

**Comment by DomT4** [comment]
Found the problem. The ` imagemagick-ruby186 ` bottles were part of the "partially-uploaded-but-not-available" batch 5 days ago when this PR was first pushed. For whatever reason, ` brew pull ` was failing to override those bottles. I just manually deleted them from Bintray, kicked off the bottle job again, and ` brew pull ` succeeded this time.

**Pull request closed without merging**
