### PR TITLE
cassandra22 2.2.7

### PR DESCRIPTION
**Pull request by tstone**
- [ Y ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [ Y ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-versions/pulls) for the same formula update/change?
- [ Y ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ Y ] Does your submission adhere to Versions "Acceptable Formulae" [guidelines](https://github.com/Homebrew/homebrew-versions/blob/07b17dfb9f1/README.md#acceptable-formulae)?
- [ N ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

No.  It does pass `brew audit`, but the strict mode returns ``depends_on` (line 13) should be put before `conflicts_with`` which is unrelated to the version change I am submitting.

-----

### CODE REVIEW

**Comment by tstone** [comment]
The build appears to be failing for an unrelated reason:

```
==> FAILED
Error: /usr/local/Library/Taps/homebrew/homebrew-core/Formula/isync.rb:9: syntax error, unexpected <<, expecting keyword_end
<<<<<<< Updated upstream
  ^
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/isync.rb:14: syntax error, unexpected ===, expecting keyword_end
=======
   ^
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/isync.rb:16: syntax error, unexpected >>, expecting keyword_end
>>>>>>> Stashed changes
```

**Comment by MikeMcQuaid** [comment]
@tstone have requeued the build.

**Comment by tstone** [comment]
@MikeMcQuaid It looks like the build script is choking on a merge conflict in homebrew-core.
https://bot.brew.sh/job/Homebrew%20Versions%20Pull%20Requests/version=el_capitan/1553/console

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request merged**
