### PR TITLE
mongodb26: fix build on OS X El Capitan (10.11)

### PR DESCRIPTION
**Pull request by asmarques**
Patch build script to include support for OS X El Capitan (10.11).

### CODE REVIEW

**Comment by jqr** [comment]
You beat me to a pull request by an hour and I like your patch better! :)

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by cordoval** [comment]
hey how can i use this PR before it gets merged

:+1: 
:+1:

**Comment by cordoval** [comment]
nvm doing it now :)

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-versions/commit/fa7d4770402811a8cbeb88040769a1972938f510. Run wild :wink:. It'd be good to get this submitted upstream given it's a very very minor change.

Thank you for your contribution to Homebrew @asmarques! :smiley_cat:

**Pull request closed without merging**
